### ISSUE TITLE
使用SharedPreferencesProvider只能中Hook到自身包名

### ISSUE THREAD

**Issue by iqiqiya** [ikws4/WeiJu#2]
可以标题表述不太正确

你好 在酷安看到的大佬 想自己模仿做一个自己用  没想到这个这么难  ORZ  太强了

就是在MainHook找不到其他app   但是mPrefFile可以打印出来全部包名  就是这个if总是不成立
`if (new XSPUtils(application, HOOK_LIST_SP).getBoolean(mPrefFile)) {
                    XposedBridge.log(mPrefFile + "在hooklist.xml中且true");
                    Log.i(TAG, "afterHookedMethod: " + mPrefFile + "在hooklist.xml中且true");
                    XSPUtils sp = new XSPUtils(application, mPrefFile);
                    new LocationHook(sp);
                } else {
                    XposedBridge.log("ssssssssssfecdcsgrvfcfgreveg");
                    Log.i(TAG, "afterHookedMethod: ;llllllkkkkkkkkkkkkkkk");`

kotlin代码看不大懂  用java模仿微聚实现的  我的水平太菜了  麻烦大佬有时间的话帮忙看下

想自己拿来学习  搞一个自己用  想增加一个模拟地理位置的功能   我尝试了几天  高德地图一直hook不到    目前只hook到自己  看看激活状态  

感激不尽   
我的全部代码：[https://github.com/iqiqiya/SecTool](https://github.com/iqiqiya/SecTool)

**Comment by ikws4** [comment]
因为你并没有在 `HookListSP` 中添加高德地图的包名，WeiJu 是在 [SelectAppActivity](https://github.com/ikws4/WeiJu/blob/1ad04e3b6b87f870fd27b783b5d34e1dcbf07a0b/app/src/main/java/io/ikws4/weiju/ui/activitys/SelectAppActivity.kt#L193) 中实现的。

使用 `HookListSP` 是因为 WeiJu 并不是一个针对单一 APP 的 XP 应用，所以需要使用一个 `SharedPreferences `文件来记录被选择的应用包名，用作是否对应用进行 Hook 的判断（就像你上面写的一样）。

但你的这个应用仅仅是为了 Hook 高德地图，所以我就不太建议使用 `HookListSP`。

以下是我的两个方法：
1. 把 if 中的条件改为直接判断是非为高德地图的包名即可
```java
if (loadPackageParam.packageName == "com.autonavi.minimap") {
    XposedBridge.log("它是高德地图，hook it!!");
    XSPUtils sp = new XSPUtils(application, mPrefFile);
    new LocationHook(sp);
} else {
    XposedBridge.log("它不是高德地图");
}
```
2. 使用一个 boolean 值来判断是否对高德地图进行Hook，然后在判断一下。
这个 boolean 值可以使用 XSPUtils 来进行存储。
```java
XSPUtils xsp = new XSPUtils(application, SECTOOL_SP);
if (xsp.getBoolean("is_hook")) {
    XposedBridge.log("hook it!!");
} else {
    XposedBridge.log("not hook");
}
```
要记得在你的UI界面调用 `xsp.setBoolean("is_hook", boolean_value)`

**Comment by iqiqiya** [comment]
了解了   有一点很奇怪  如果我使用HookListSP的方式   

就hook不到其他app   只能hook到sectool本身

想问下如果要hook多个app怎么改呢

非常感谢

**Comment by ikws4** [comment]
> 了解了 有一点很奇怪 如果我使用HookListSP的方式
> 
> 就hook不到其他app 只能hook到sectool本身
> 
> 想问下如果要hook多个app怎么改呢
> 
> 非常感谢

[在你的UI界面调用这行代码，把你要 Hook 的 APP 包名添加进去就好了](https://github.com/ikws4/WeiJu/blob/1ad04e3b6b87f870fd27b783b5d34e1dcbf07a0b/app/src/main/java/io/ikws4/weiju/ui/activitys/SelectAppActivity.kt#L194)

**Comment by iqiqiya** [comment]
这个添加操作我是有的   放在了这里 
https://github.com/iqiqiya/SecTool/blame/master/app/src/main/java/com/iakie/sectool/ui/fragments/BFragment.java
![image](https://user-images.githubusercontent.com/43666095/77641523-26cdfc80-6f97-11ea-8cee-efae13599b99.png)

使用文件管理器是可以看到hook_list.xml里边添加成功了的

但是MainHook那里  使用`if (new XSPUtils(application, HOOK_LIST_SP).getBoolean(mPrefFile)) {`
是检索不到里边的app   无法判断是true
![image](https://user-images.githubusercontent.com/43666095/77641765-8f1cde00-6f97-11ea-80b6-54f61825f47b.png)

比如说现在hook_list.xml文件内容是有这么多条
![image](https://user-images.githubusercontent.com/43666095/77642150-271ac780-6f98-11ea-880e-aadd8e3cd6ee.png)

但是MainHook只能判断出  com.iakie.sectool，也就是app本身是true，其他的就像没添加一样

现在问题就在这里   一直无法从hook_list.xml判断其他app状态

**Comment by iqiqiya** [comment]
我发现 原来是手机的锅   刚才换了个手机好了  麻烦了小哥哥  我好笨

**Comment by ikws4** [comment]
Use Instrumentation.callApplicationOnCreate
```kotlin
Instrumentation::class.java.hookMethod("callApplicationOnCreate", Application::class.java) { param ->
    val application = param.args[0] as Application
}
```
to replace Application.onCreate, then use this application object to call contentResolver.
