### ISSUE TITLE
DPI修改功能对所有Chrome和Chromium核浏览器无效

### ISSUE THREAD

**Issue by Gokou-Ruri** [ikws4/WeiJu#7]
经测试，无论将DPI值设置为多少，对Chrome Stable v83、Kiwi v77均无效，猜测大概对所有非魔改版的Chrome/Chromium核浏览器均无效。（每次修改DPI值后都会手动force-stop再启动浏览器）
对快图等其它程序有效，应该不是我的手机系统问题。

PS：系统DP（非DPI）值≥600时，Chrome（核）浏览器会变成类似PC版本的外观。DP值<600时，则会恢复成普通的手机样式外观。在我的手机上， DPI=384 时，DP=600  这时Chrome浏览器和Kiwi浏览器就会变成下面这样样。
![Screenshot_Chrome_20200629-103702](https://user-images.githubusercontent.com/26711804/85967468-1e9db700-b9f5-11ea-861b-f5c169b645e4.png)

**Comment by ikws4** [comment]
重复的 issue [#5](https://github.com/ikws4/WeiJu/issues/5)

**Comment by Gokou-Ruri** [comment]
> 重复的 issue [#5](https://github.com/ikws4/WeiJu/issues/5)

感谢回复，本issues是为了顺带报告Chrome相关问题——推测Chrome系浏览器大概是检测DP而不是DPI。
